import = [
    "~/.config/alacritty/themes/tokyonight_night.toml"
]

[window]
#decorations =  "Buttonless"
padding = { y = 8, x = 8}

[font]
normal = { family = "Hack Nerd Font Mono", style ="Regular" }
bold = { family = "Hack Nerd Font Mono", style ="Bold" }
italic = { family = "Hack Nerd Font Mono", style ="Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style ="BoldItalic" }
