include default.conf

font_family FiraCode Nerd Font
font_size 14.0

tab_bar_style powerline
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
tab_powerline_style round
inactive_text_alpha 0.7

enabled_layouts tall:bias=60;full_size=1;mirrored=false,fat:bias=70,stack
hide_window_decorations yes
macos_option_as_alt yes
confirm_os_window_close 0

include ~/.local/share/nvim/lazy/tokyonight.nvim/extras/kitty/tokyonight_night.conf
 
draw_minimal_borders yes
active_border_color #666666
inactive_border_color #000000
window_padding_width 0

allow_remote_control yes
