include default.conf


#font_family JetBrainsMono Nerd Font Mono
#font_family Hack Nerd Font Mono Regular
font_family FiraCode Nerd Font
font_size 14.0

tab_bar_style powerline
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
tab_powerline_style round
inactive_text_alpha 0.7

enabled_layouts tall:bias=60;full_size=1;mirrored=false,fat:bias=70,stack
hide_window_decorations yes
macos_option_as_alt yes
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
#
 
background_tint 0.8
background: #000000
background_image /Users/thiagofelix/Downloads/deathstar.png
background_image_layout tiled
draw_minimal_borders no
active_border_color #666666
inactive_border_color #000000
window_padding_width 5

